// recetas.js

const recetas = [
  {
    id: "pasta-carbonara",
    titulo: "Pasta Carbonara",
    categoria: "pastas",
    imagen: "/assets/pasta-carbonara.png",
    descripcion:
      "La clásica receta italiana con panceta o guanciale y parmesano.",
    tiempo: "20 min",
    destacada: true,
  },
  {
    id: "pasta-pesto",
    titulo: "Pasta al Pesto",
    categoria: "pastas",
    imagen: "/assets/pasta-pesto.png",
    descripcion: "Pasta fresca con salsa de albahaca casera.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "pasta-bolonesa",
    titulo: "Pasta a la Boloñesa",
    categoria: "pastas",
    imagen: "/assets/pasta-bolonesa.png",
    descripcion: "Pasta con salsa boloñesa tradicional con carne y verduras.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "guacamole",
    titulo: "Guacamole Casero",
    categoria: "aperitivos",
    imagen: "/assets/guacamole.png",
    descripcion: "Dip mexicano de aguacate cremoso y sabroso.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "bruschetta-tomate",
    titulo: "Bruschetta de Tomate",
    categoria: "aperitivos",
    imagen: "/assets/bruschetta-tomate.png",
    descripcion: "Tostas italianas con tomate, ajo y albahaca.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "paella-valenciana",
    titulo: "Paella Valenciana",
    categoria: "arroces-y-risottos",
    imagen: "/assets/paella-valenciana.png",
    descripcion: "La clásica paella con pollo, conejo y verduras.",
    tiempo: "60 min",
    destacada: false,
  },
  {
    id: "risotto-setas",
    titulo: "Risotto de Setas",
    categoria: "arroces-y-risottos",
    imagen: "/assets/risotto-setas.png",
    descripcion: "Cremoso risotto italiano con setas variadas.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "ramen",
    titulo: "Ramen Japonés",
    categoria: "asiatica",
    imagen: "/assets/ramen.png",
    descripcion: "Sopa japonesa con fideos, caldo y toppings.",
    tiempo: "45 min",
    destacada: false,
  },
  {
    id: "pollo-teriyaki",
    titulo: "Pollo Teriyaki",
    categoria: "asiatica",
    imagen: "/assets/pollo-teriyaki.png",
    descripcion: "Pollo glaseado con salsa teriyaki japonesa.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "hamburguesa-clasica",
    titulo: "Hamburguesa Clásica",
    categoria: "burgers",
    imagen: "/assets/hamburguesa-clasica.png",
    descripcion: "Carne jugosa, queso, tomate, lechuga y pan brioche.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "smash-burger",
    titulo: "Smash Burger",
    categoria: "burgers",
    imagen: "/assets/smash-burger.png",
    descripcion: "Hamburguesa smasheada con queso cheddar fundido.",
    tiempo: "8 min",
    destacada: false,
  },
  {
    id: "entrecot-parrilla",
    titulo: "Entrecot a la Parrilla",
    categoria: "carnes",
    imagen: "/assets/entrecot-parrilla.png",
    descripcion: "Carne jugosa cocinada al punto perfecto.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "albondigas-salsa",
    titulo: "Albóndigas en Salsa",
    categoria: "carnes",
    imagen: "/assets/albondigas-salsa.png",
    descripcion: "Albóndigas caseras en salsa de tomate.",
    tiempo: "35 min",
    destacada: false,
  },
  {
    id: "ensalada-cesar",
    titulo: "Ensalada César",
    categoria: "ensaladas",
    imagen: "/assets/ensalada-cesar.png",
    descripcion: "Lechuga, pollo, croutons y salsa césar.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "ensalada-caprese",
    titulo: "Ensalada Caprese",
    categoria: "ensaladas",
    imagen: "/assets/ensalada-caprese.png",
    descripcion: "Mozzarella, tomate y albahaca fresca.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "tacos-carne",
    titulo: "Tacos de Carne Asada",
    categoria: "mexicana",
    imagen: "/assets/tacos-carne.png",
    descripcion: "Tacos tradicionales con carne marinada y salsas.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "quesadillas-queso",
    titulo: "Quesadillas de Queso",
    categoria: "mexicana",
    imagen: "/assets/quesadillas-queso.png",
    descripcion: "Tortillas doradas con queso fundido.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "salmon-plancha",
    titulo: "Salmón a la Plancha",
    categoria: "pescado-y-marisco",
    imagen: "/assets/salmon-plancha.png",
    descripcion: "Salmón crujiente por fuera y jugoso por dentro.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "paella-marisco",
    titulo: "Paella de Marisco",
    categoria: "pescado-y-marisco",
    imagen: "/assets/paella-marisco.png",
    descripcion: "Paella con mariscos frescos y caldo casero.",
    tiempo: "50 min",
    destacada: false,
  },
  {
    id: "pizza-margarita",
    titulo: "Pizza Margarita",
    categoria: "pizza",
    imagen: "/assets/pizza-margarita.png",
    descripcion: "Pizza clásica con tomate, mozzarella y albahaca.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "pizza-cuatro-quesos",
    titulo: "Pizza Cuatro Quesos",
    categoria: "pizza",
    imagen: "/assets/pizza-cuatro-quesos.png",
    descripcion: "Deliciosa mezcla de cuatro quesos fundidos.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "pollo-al-horno",
    titulo: "Pollo al Horno",
    categoria: "pollo",
    imagen: "/assets/pollo-al-horno.png",
    descripcion: "Muslos de pollo horneados con hierbas.",
    tiempo: "40 min",
    destacada: false,
  },
  {
    id: "nuggets-caseros",
    titulo: "Nuggets Caseros",
    categoria: "pollo",
    imagen: "/assets/nuggets-caseros.png",
    descripcion: "Crujientes nuggets de pollo hechos en casa.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "tarta-queso",
    titulo: "Tarta de Queso",
    categoria: "postres",
    imagen: "/assets/tarta-queso.png",
    descripcion: "Tarta cremosa al horno con base de galleta.",
    tiempo: "50 min",
    destacada: false,
  },
  {
    id: "mousse-chocolate",
    titulo: "Mousse de Chocolate",
    categoria: "postres",
    imagen: "/assets/mousse-chocolate.png",
    descripcion: "Mousse esponjoso y rico en cacao.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "salsa-pesto",
    titulo: "Salsa Pesto",
    categoria: "salsas",
    imagen: "/assets/salsa-pesto.png",
    descripcion: "Salsa italiana con albahaca y piñones.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "salsa-bechamel",
    titulo: "Salsa Bechamel",
    categoria: "salsas",
    imagen: "/assets/salsa-bechamel.png",
    descripcion: "Salsa blanca para gratinados y lasañas.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "crema-calabaza",
    titulo: "Crema de Calabaza",
    categoria: "sopas-y-cremas",
    imagen: "/assets/crema-calabaza.png",
    descripcion: "Crema suave y reconfortante para el invierno.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "sopa-pollo",
    titulo: "Sopa de Pollo Casera",
    categoria: "sopas-y-cremas",
    imagen: "/assets/sopa-pollo.png",
    descripcion: "Sopa reconfortante con pollo y verduras.",
    tiempo: "40 min",
    destacada: false,
  },
  {
    id: "wraps-pollo",
    titulo: "Wraps de Pollo",
    categoria: "wraps-y-sandwiches",
    imagen: "/assets/wraps-pollo.png",
    descripcion: "Wraps frescos con tiras de pollo y vegetales.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "sandwich-mixto",
    titulo: "Sándwich Mixto",
    categoria: "wraps-y-sandwiches",
    imagen: "/assets/sandwich-mixto.png",
    descripcion: "Clásico sándwich de jamón y queso a la plancha.",
    tiempo: "10 min",
    destacada: false,
  }
];
