// recetas.js

const recetas = [
  {
    id: "pasta-carbonara",
    titulo: "Pasta Carbonara",
    categoria: "pastas",
    imagen: "pasta-carbonara.png",
    descripcion:
      "La clásica receta italiana con panceta o guanciale y parmesano.",
    tiempo: "20 min",
    destacada: true,
  },
  {
    id: "pasta-pesto",
    titulo: "Pasta al Pesto",
    categoria: "pastas",
    imagen: "pasta-pesto.png",
    descripcion: "Pasta fresca con salsa de albahaca casera.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "pasta-bolonesa",
    titulo: "Pasta a la Boloñesa",
    categoria: "pastas",
    imagen: "pasta-bolonesa.png",
    descripcion: "Pasta con salsa boloñesa tradicional con carne y verduras.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "guacamole",
    titulo: "Guacamole Casero",
    categoria: "aperitivos",
    imagen: "guacamole.png",
    descripcion: "Dip mexicano de aguacate cremoso y sabroso.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "bruschetta-tomate",
    titulo: "Bruschetta de Tomate",
    categoria: "aperitivos",
    imagen: "bruschetta-tomate.png",
    descripcion: "Tostas italianas con tomate, ajo y albahaca.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "paella-valenciana",
    titulo: "Paella Valenciana",
    categoria: "arroces-y-risottos",
    imagen: "paella-valenciana.png",
    descripcion: "La clásica paella con pollo, conejo y verduras.",
    tiempo: "60 min",
    destacada: false,
  },
  {
    id: "risotto-setas",
    titulo: "Risotto de Setas",
    categoria: "arroces-y-risottos",
    imagen: "risotto-setas.png",
    descripcion: "Cremoso risotto italiano con setas variadas.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "ramen",
    titulo: "Ramen Japonés",
    categoria: "asiatica",
    imagen: "ramen.png",
    descripcion: "Sopa japonesa con fideos, caldo y toppings.",
    tiempo: "45 min",
    destacada: false,
  },
  {
    id: "pollo-teriyaki",
    titulo: "Pollo Teriyaki",
    categoria: "asiatica",
    imagen: "pollo-teriyaki.png",
    descripcion: "Pollo glaseado con salsa teriyaki japonesa.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "hamburguesa-clasica",
    titulo: "Hamburguesa Clásica",
    categoria: "burgers",
    imagen: "hamburguesa-clasica.png",
    descripcion: "Carne jugosa, queso, tomate, lechuga y pan brioche.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "smash-burger",
    titulo: "Smash Burger",
    categoria: "burgers",
    imagen: "smash-burger.png",
    descripcion: "Hamburguesa smasheada con queso cheddar fundido.",
    tiempo: "8 min",
    destacada: false,
  },
  {
    id: "entrecot-parrilla",
    titulo: "Entrecot a la Parrilla",
    categoria: "carnes",
    imagen: "entrecot-parrilla.png",
    descripcion: "Carne jugosa cocinada al punto perfecto.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "costillas-barbacoa",
    titulo: "Costillas a la Barbacoa",
    categoria: "carnes",
    imagen: "costillas-barbacoa.png",
    descripcion: "Costillas tiernas con salsa barbacoa.",
    tiempo: "3 - 4 h",
    destacada: false,
  },
  {
    id: "ensalada-cesar",
    titulo: "Ensalada César",
    categoria: "ensaladas",
    imagen: "ensalada-cesar.png",
    descripcion: "Lechuga, pollo, croutons y salsa césar.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "ensalada-caprese",
    titulo: "Ensalada Caprese",
    categoria: "ensaladas",
    imagen: "ensalada-caprese.png",
    descripcion: "Mozzarella, tomate y albahaca fresca.",
    tiempo: "10 min",
    destacada: false,
  },
  {
    id: "tacos-carne",
    titulo: "Tacos de Carne Asada",
    categoria: "mexicana",
    imagen: "tacos-carne.png",
    descripcion: "Tacos tradicionales con carne marinada y salsas.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "quesadillas-queso",
    titulo: "Quesadillas de Queso",
    categoria: "mexicana",
    imagen: "quesadillas-queso.png",
    descripcion: "Tortillas doradas con queso fundido.",
    tiempo: "15 min",
    destacada: false,
  },
  {
    id: "salmon-plancha",
    titulo: "Salmón a la Plancha",
    categoria: "pescado-y-marisco",
    imagen: "salmon-plancha.png",
    descripcion: "Salmón crujiente por fuera y jugoso por dentro.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "mejillones-vapor",
    titulo: "Mejillones al Vapor",
    categoria: "pescado-y-marisco",
    imagen: "mejillones-vapor.png",
    descripcion: "Mejillones cocidos al vapor con hierbas y limón.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "pizza-margarita",
    titulo: "Pizza Margarita",
    categoria: "pizza",
    imagen: "pizza-margarita.png",
    descripcion: "Pizza clásica con tomate, mozzarella y albahaca.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "pizza-cuatro-quesos",
    titulo: "Pizza Cuatro Quesos",
    categoria: "pizza",
    imagen: "pizza-cuatro-quesos.png",
    descripcion: "Deliciosa mezcla de cuatro quesos fundidos.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "pollo-al-horno",
    titulo: "Pollo al Horno",
    categoria: "pollo",
    imagen: "pollo-al-horno.png",
    descripcion: "Muslos de pollo horneados con hierbas.",
    tiempo: "40 min",
    destacada: false,
  },
  {
    id: "pollo-crunchy",
    titulo: "Pollo Crunchy",
    categoria: "pollo",
    imagen: "pollo-crunchy.png",
    descripcion: "Crujientes trozos de pollo empanado.",
    tiempo: "25 min",
    destacada: false,
  },
  {
    id: "tarta-queso",
    titulo: "Tarta de Queso",
    categoria: "postres",
    imagen: "tarta-queso.png",
    descripcion: "Tarta cremosa al horno con base de galleta.",
    tiempo: "50 min",
    destacada: false,
  },
  {
    id: "mousse-chocolate",
    titulo: "Mousse de Chocolate",
    categoria: "postres",
    imagen: "mousse-chocolate.png",
    descripcion: "Mousse esponjoso y rico en cacao.",
    tiempo: "20 min",
    destacada: false,
  },
{
  id: "spicy-mayo",
  titulo: "Spicy Mayo",
  categoria: "salsas",
  imagen: "spicy-mayo.png",
  descripcion: "Mayonesa cremosa con un toque picante al estilo japonés.",
  tiempo: "5 min",
  destacada: false,
},
{
  id: "salsa-burger",
  titulo: "Salsa Burger",
  categoria: "salsas",
  imagen: "salsa-burger.png",
  descripcion: "Salsa cremosa y sabrosa perfecta para hamburguesas caseras.",
  tiempo: "10 min",
  destacada: false,
},

  {
    id: "crema-calabaza",
    titulo: "Crema de Calabaza",
    categoria: "sopas-y-cremas",
    imagen: "crema-calabaza.png",
    descripcion: "Crema suave y reconfortante para el invierno.",
    tiempo: "30 min",
    destacada: false,
  },
  {
    id: "sopa-pollo",
    titulo: "Sopa de Pollo Casera",
    categoria: "sopas-y-cremas",
    imagen: "sopa-pollo.png",
    descripcion: "Sopa reconfortante con pollo y verduras.",
    tiempo: "40 min",
    destacada: false,
  },
  {
    id: "wraps-pollo",
    titulo: "Wraps de Pollo",
    categoria: "wraps-y-sandwiches",
    imagen: "wraps-pollo.png",
    descripcion: "Wraps frescos con tiras de pollo y vegetales.",
    tiempo: "20 min",
    destacada: false,
  },
  {
    id: "sandwich-mixto",
    titulo: "Sándwich Mixto",
    categoria: "wraps-y-sandwiches",
    imagen: "sandwich-mixto.png",
    descripcion: "Clásico sándwich de jamón y queso a la plancha.",
    tiempo: "10 min",
    destacada: false,
  }
];
